services:
  - docker:dind

stages:
  - build
  - release
  - staging
  - production

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://localhost:2375"

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build:
  stage: build
  image: docker:stable
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF --cache-from $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  except:
    - tags

release-name:
  stage: release
  image: docker:stable
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  except:
    - master

release-master:
  stage: release
  image: docker:stable
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF $CI_REGISTRY_IMAGE:stable
    - docker push $CI_REGISTRY_IMAGE:stable
  only:
    - master

.common-deploy-script: &common-deploy-script
  script:
    - |
      helm upgrade helm-chart/joelathiessen.ca
      --install 
      --force 
      --set nameOverride=${NAME}
      --namespace=${NAMESPACE}

deploy-staging:
  stage: staging
  image: registry.joelathiessen.ca/kaly2/joelathiessen.ca/jbuild
  variables:
    NAME: "joelathiessen-ca"
    NAMESPACE: "staging"
  <<: *common-deploy-script
  environment:
    name: staging
    url: https://staging.joelathiessen.ca
  except:
    - master

deploy-production:
  stage: production
  image: registry.joelathiessen.ca/kaly2/joelathiessen.ca/jbuild
  variables:
    NAME: "joelathiessen-ca"
    NAMESPACE: "prod"
  <<: *common-deploy-script
  environment:
    name: production
    url: https://prod.joelathiessen.ca
  only:
    - master
